version: "3"

services: 
  mongo: 
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db

  minio: 
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    volumes:
      - ./minio/upload:/export
    command: server /export

  server: 
    image: crescent-conglomerate
    build: express
    container_name: server
    ports:
      - "4001:4001"
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - minio 
      - mongo
