version: "3"

services: 
  mongo: 
    image: mongo:latest
    container_name: mongo
    ports:
      - "${MONGO_HOST_PORT}:27017"
    volumes:
      - ./mongodb:/data/db

  minio: 
    image: minio/minio:latest
    container_name: minio
    ports:
      - "${MINIO_HOST_PORT}:9000"
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    volumes:
      - ./minio/upload:/export
    command: server /export

  server: 
    image: crescent-conglomerate
    build: express
    container_name: server
    expose:
      - ${EXPRESS_PORT}
      - ${GRAPHQL_PORT}
    ports:
      - "${EXPRESS_PORT}:${EXPRESS_PORT}"
      - "${GRAPHQL_PORT}:${GRAPHQL_PORT}"
    volumes:
      - .:/usr/src/app
    depends_on:
      - minio 
      - mongo
