version: "2"

services: 
  mongo: 
    image: mongo:latest
    container_name: mongo
    ports:
      - "${MONGO_HOST_PORT}:27017"
    volumes:
      - ./mongodb:/data/db

  minio: 
    image: minio/minio:latest
    container_name: minio
    ports:
      - "${MINIO_HOST_PORT}:9000"
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    volumes:
      - ./minio/upload:/export
    command: server /export

  server: 
    image: crescentdev/crescent-conglomerate
    privileged: true
    build: express
    container_name: server
    expose:
      - ${EXPRESS_PORT}
      - ${GRAPHQL_PORT}
    ports:
      - "${EXPRESS_PORT}:${EXPRESS_PORT}"
      - "${GRAPHQL_PORT}:${GRAPHQL_PORT}"
    volumes:
      - .:/usr/src/app
    depends_on:
      - minio 
      - mongo

  wes-server:
    image: candig/wes-server:${WES_VERSION}
    container_name: wes-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /var/lib/docker/volumes:/var/lib/docker/volumes:rw
      - /tmp:/tmp:rw
      - /var/lib/toil:/var/lib/toil:rw
    ports:
      - "${WES_PORT}:8081"
    entrypoint: ["wes-server"]
    command:
      - --port=8081
      - --backend=${WES_BACKEND}
      - --opt=runner=${WES_CWL_RUNNER}
      - --opt=extra=--writeLogs=/
      - --opt=extra=--writeLogsFromAllJobs
      - --opt=extra=--maxLogFileSize=0 
      - --opt=extra=--writeLogsFromAllJobs

